export const DASHBOARD_PATH = '/'
export const LOGIN_PATH = '/login'
export const REGISTER_PATH = '/register'
export const PRODUCT_PATH = '/products'
export const USER_PATH = '/users'
export const NOT_FOUND_PATH = '/not-found'
export const BUTTON_PATH = '/buttons'
export const STATUS_PATH = '/statuses'